- Move RTC and PIC emulation back to monitor

diff --git a/configs/ramdisk/init b/configs/ramdisk/init
--- a/configs/ramdisk/init
+++ b/configs/ramdisk/init
@@ -14,8 +14,8 @@ mount -t proc -o nodev,noexec,nosuid none /proc
 
 echo "Starting QEMU scripts..."
 
-#mkdir -p /media1/
-mount -t ext2 /dev/ide/host0/bus0/target0/lun0/part2 /media1/
+mkdir -p /media1/
+mount -t ext2 /dev/ide/host2/bus0/target0/lun0/part5 /media1/
 
 #create dev files
 mknod -m 0644 /dev/ttyS0 c 4 64 
@@ -38,7 +38,7 @@ mknod -m 0777 /dev/net/tun c 10 200
 /sbin/ifconfig eth0 down
 /usr/sbin/brctl addbr br0
 /sbin/ifconfig eth0 0.0.0.0 promisc up
-/sbin/ifconfig br0 141.3.40.155 netmask 255.255.255.0 broadcast 141.3.40.255 up
+/sbin/ifconfig br0 141.3.40.154 netmask 255.255.255.0 broadcast 141.3.40.255 up
 /usr/sbin/brctl stp br0 0
 /usr/sbin/brctl setfd br0 1
 /usr/sbin/brctl sethello br0 1
@@ -49,4 +49,10 @@ mknod -m 0777 /dev/net/tun c 10 200
 #network options:
 #-net nic,vlan=1,macaddr=00:16:3e:5a:af:2a,model=rtl8139 -net tap,vlan=1,bridge=br0
 
-/bin/qemu-dm -vcpus 1 -vnc 141.3.40.155:0 -k de -monitor stdio -usb -serial /dev/ttyS0 -net nic,vlan=1,macaddr=00:16:3e:5a:af:2a,model=rtl8139 -net tap,vlan=1
+[ -e /media1/linux.img ] || echo "winxp.img not found"
+
+/bin/qemu-dm -std-vga -vcpus 1 -boot c -vnc 141.3.40.154:0 -k de -pci yes -monitor stdio /media1/winxp-noapic.img
+
+umount /media1/
+echo "QEMU successfully shutdown"
+
